[package]
name = "cli-radio"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.17" # Use cpal backend, no wasapi
minimp3 = "0.5"
reqwest = { version = "0.11", features = ["blocking"] }
crossterm = "0.27"